live_config_reload = true

[font]
size = 19.0

[shell]
program = "/usr/local/bin/fish"
# program = "/opt/homebrew/bin/fish" # mac
args = ["-l", "-c", "tmux attach || tmux"]

[window.padding]
x = 18
y = 18

